Client: Hotfix for Angular 10 compilation issues
It seems that we must force version 2.0 of tslib, otherwise we get build errors along the lines of the following:

* `Module build failed: TypeError: loaderUtils.getOptions is not a function`
* `(Emitted value instead of an instance of Error) CssSyntaxError:`